// Code generated by "enumer -type RequestMethod -trimprefix Method -json -text"; DO NOT EDIT.

package pulsetictypes

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _RequestMethodName = "HEADGETPOSTPUTPATCHDELETEOPTIONS"

var _RequestMethodIndex = [...]uint8{0, 4, 7, 11, 14, 19, 25, 32}

const _RequestMethodLowerName = "headgetpostputpatchdeleteoptions"

func (i RequestMethod) String() string {
	if i >= RequestMethod(len(_RequestMethodIndex)-1) {
		return fmt.Sprintf("RequestMethod(%d)", i)
	}
	return _RequestMethodName[_RequestMethodIndex[i]:_RequestMethodIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RequestMethodNoOp() {
	var x [1]struct{}
	_ = x[MethodHEAD-(0)]
	_ = x[MethodGET-(1)]
	_ = x[MethodPOST-(2)]
	_ = x[MethodPUT-(3)]
	_ = x[MethodPATCH-(4)]
	_ = x[MethodDELETE-(5)]
	_ = x[MethodOPTIONS-(6)]
}

var _RequestMethodValues = []RequestMethod{MethodHEAD, MethodGET, MethodPOST, MethodPUT, MethodPATCH, MethodDELETE, MethodOPTIONS}

var _RequestMethodNameToValueMap = map[string]RequestMethod{
	_RequestMethodName[0:4]:        MethodHEAD,
	_RequestMethodLowerName[0:4]:   MethodHEAD,
	_RequestMethodName[4:7]:        MethodGET,
	_RequestMethodLowerName[4:7]:   MethodGET,
	_RequestMethodName[7:11]:       MethodPOST,
	_RequestMethodLowerName[7:11]:  MethodPOST,
	_RequestMethodName[11:14]:      MethodPUT,
	_RequestMethodLowerName[11:14]: MethodPUT,
	_RequestMethodName[14:19]:      MethodPATCH,
	_RequestMethodLowerName[14:19]: MethodPATCH,
	_RequestMethodName[19:25]:      MethodDELETE,
	_RequestMethodLowerName[19:25]: MethodDELETE,
	_RequestMethodName[25:32]:      MethodOPTIONS,
	_RequestMethodLowerName[25:32]: MethodOPTIONS,
}

var _RequestMethodNames = []string{
	_RequestMethodName[0:4],
	_RequestMethodName[4:7],
	_RequestMethodName[7:11],
	_RequestMethodName[11:14],
	_RequestMethodName[14:19],
	_RequestMethodName[19:25],
	_RequestMethodName[25:32],
}

// RequestMethodString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RequestMethodString(s string) (RequestMethod, error) {
	if val, ok := _RequestMethodNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RequestMethodNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RequestMethod values", s)
}

// RequestMethodValues returns all values of the enum
func RequestMethodValues() []RequestMethod {
	return _RequestMethodValues
}

// RequestMethodStrings returns a slice of all String values of the enum
func RequestMethodStrings() []string {
	strs := make([]string, len(_RequestMethodNames))
	copy(strs, _RequestMethodNames)
	return strs
}

// IsARequestMethod returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RequestMethod) IsARequestMethod() bool {
	for _, v := range _RequestMethodValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for RequestMethod
func (i RequestMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for RequestMethod
func (i *RequestMethod) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("RequestMethod should be a string, got %s", data)
	}

	var err error
	*i, err = RequestMethodString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for RequestMethod
func (i RequestMethod) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for RequestMethod
func (i *RequestMethod) UnmarshalText(text []byte) error {
	var err error
	*i, err = RequestMethodString(string(text))
	return err
}
