// Code generated by "enumer -type RequestType -trimprefix RequestType -json -text"; DO NOT EDIT.

package pulsetictypes

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _RequestTypeName = "HTTPTCPICMP"

var _RequestTypeIndex = [...]uint8{0, 4, 7, 11}

const _RequestTypeLowerName = "httptcpicmp"

func (i RequestType) String() string {
	if i >= RequestType(len(_RequestTypeIndex)-1) {
		return fmt.Sprintf("RequestType(%d)", i)
	}
	return _RequestTypeName[_RequestTypeIndex[i]:_RequestTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RequestTypeNoOp() {
	var x [1]struct{}
	_ = x[RequestTypeHTTP-(0)]
	_ = x[RequestTypeTCP-(1)]
	_ = x[RequestTypeICMP-(2)]
}

var _RequestTypeValues = []RequestType{RequestTypeHTTP, RequestTypeTCP, RequestTypeICMP}

var _RequestTypeNameToValueMap = map[string]RequestType{
	_RequestTypeName[0:4]:       RequestTypeHTTP,
	_RequestTypeLowerName[0:4]:  RequestTypeHTTP,
	_RequestTypeName[4:7]:       RequestTypeTCP,
	_RequestTypeLowerName[4:7]:  RequestTypeTCP,
	_RequestTypeName[7:11]:      RequestTypeICMP,
	_RequestTypeLowerName[7:11]: RequestTypeICMP,
}

var _RequestTypeNames = []string{
	_RequestTypeName[0:4],
	_RequestTypeName[4:7],
	_RequestTypeName[7:11],
}

// RequestTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RequestTypeString(s string) (RequestType, error) {
	if val, ok := _RequestTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RequestTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RequestType values", s)
}

// RequestTypeValues returns all values of the enum
func RequestTypeValues() []RequestType {
	return _RequestTypeValues
}

// RequestTypeStrings returns a slice of all String values of the enum
func RequestTypeStrings() []string {
	strs := make([]string, len(_RequestTypeNames))
	copy(strs, _RequestTypeNames)
	return strs
}

// IsARequestType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RequestType) IsARequestType() bool {
	for _, v := range _RequestTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for RequestType
func (i RequestType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for RequestType
func (i *RequestType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("RequestType should be a string, got %s", data)
	}

	var err error
	*i, err = RequestTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for RequestType
func (i RequestType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for RequestType
func (i *RequestType) UnmarshalText(text []byte) error {
	var err error
	*i, err = RequestTypeString(string(text))
	return err
}
