apiVersion: pulsetic.clevyr.com/v1
kind: Account
metadata:
  labels:
    app.kubernetes.io/name: pulsetic-operator
    app.kubernetes.io/managed-by: kustomize
  name: example
spec:
  isDefault: true
  apiKeySecretRef:
    name: pulsetic-example
    key: apiKey
